### ISSUE TITLE
Missing sotopia environment in td3.py

### ISSUE THREAD

**Issue by Bohemianc** [likenneth/dialogue_action_token#1]
Hello,

Nice work! The `td3.py` file seems to be missing the sotopia environment. Is there a need to modify the code, or was the file not included in the upload?

**Comment by likenneth** [comment]
Currently we haven't added the option to experiemnt on Sotopia in td3.py. Technically speaking, it should be easy as all we need to do is swap in the environment class defined in envs/sot_env.py.
