### ISSUE TITLE
Pre-collected episodes for sotopia and buffer IDX

### ISSUE THREAD

**Issue by lxqpku** [likenneth/dialogue_action_token#2]
Hi, I wonder whether the generated episodes from sotopia env can be openly released. 
In addition, does it mean that we need to collect 159 (from 0 to 158 idx) buffers to store the episodes?
(The pre-collected data for redteaming is only from buffer_0? And there is another 158 buffer data that needs to be trained via td3?)

**Comment by likenneth** [comment]
Hi I will work on releasing the pre-generated episodes from Sotopia. 

For training, you don't have to have 159 buffers. If the training data is constrained on one scenario (out of 159), then the RL trains the planner to specialize on that single scenario. This applies to both Sotopia and red-teaming.

**Comment by lxqpku** [comment]
Really appreciate your work and thanks a lot? And another question: Can the trained planner on one single scenario (sotopia/redteaming) be generalized to other scenarios within one environment?
