### ISSUE TITLE
mean and variance of the states

### ISSUE THREAD

**Issue by Bohemianc** [likenneth/dialogue_action_token#4]
Hi likenneth,

I noticed that you computed the mean and variance of the states for the LLaMA model. Could you share how you calculated these? For example, were they computed per layer, across the whole dataset, or on a subset?

I’m working with a different LLM and would like to adapt your approach. Thanks!

**Comment by likenneth** [comment]
It solely depends on what serves as the input to the controller MLP (which takes in "states" and output "action"). In our case, we used the last layer last token embedding of the conversation history.

**Comment by Bohemianc** [comment]
Thanks for the quick reply! Just to confirm, do you mean the mean and variance of states are calculated based on the offline dataset for RL training? Specifically, are they computed by taking the mean and variance of the state (last layer last token embedding of the conversation history) for each datapoint in the offline dataset?

**Comment by likenneth** [comment]
Yes, using an offline dataset will be the best.
